GET http://127.0.0.1:8000/products/ HTTP/1.1


###
GET http://127.0.0.1:8000/product/1 HTTP/1.1


###
PUT http://127.0.0.1:8000/product/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NTEzODEyLCJpYXQiOjE3MzY1MTM1MTIsImp0aSI6IjlmOTg1YmZmMDkzMzRiZDM4ZWFiMzY4Njg3NWIyYTc1IiwidXNlcl9pZCI6MX0.-zTr9EgAG6XWbVO32kKRwxs28ul4NktPGpDcW5-lO3s

{
    "name": "Television",
    "price": 300.00,
    "stock": 15,
    "description": "An amazing new TV"
}

###
DELETE  http://127.0.0.1:8000/product/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NTEzODEyLCJpYXQiOjE3MzY1MTM1MTIsImp0aSI6IjlmOTg1YmZmMDkzMzRiZDM4ZWFiMzY4Njg3NWIyYTc1IiwidXNlcl9pZCI6MX0.-zTr9EgAG6XWbVO32kKRwxs28ul4NktPGpDcW5-lO3s


###
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NDg1NDUwLCJpYXQiOjE3MzY0ODUxNTAsImp0aSI6IjkxMWE0ZGI5MDkyMjQ5OTdhMWIyNmQzYjhjZjNjN2U3IiwidXNlcl9pZCI6MX0.aoIQYGP41T6p2owvme_6zUDYfsSmuIqx1YLXN3h1E0Q
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NTEzODEyLCJpYXQiOjE3MzY1MTM1MTIsImp0aSI6IjlmOTg1YmZmMDkzMzRiZDM4ZWFiMzY4Njg3NWIyYTc1IiwidXNlcl9pZCI6MX0.-zTr9EgAG6XWbVO32kKRwxs28ul4NktPGpDcW5-lO3s

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json
#Will renew the old token and returns new access token
{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNjU3Nzc1MCwiaWF0IjoxNzM2NDkxMzUwLCJqdGkiOiI5NDhlNGZkNDA5N2Q0MWZhOGQ2ODhlODIyYjI0ZmJhOCIsInVzZXJfaWQiOjJ9.R6U7IfrWt5M77dNJYbeTRMiZexFtJ3lo9sto-kWzcbM"
}